---
- name: checking to see if already clustered
  stat:
    path: /etc/rabbitmq/clustered
  register: clustered

- name: Manage RabbitMQ clustering
  include_tasks: rabbitmq_clustering.yml
  when: >
        rabbitmq_enable_clustering and
        not clustered['stat']['exists']