---
- name: Configure RabbitMQ
  include_tasks: config.yml
  when: rabbitmq_config_service

- name: Manage RabbitMQ virtual hosts
  include_tasks: rabbitmq_vhosts.yml
  when: rabbitmq_extra_vhosts is defined

- name: Configure RabbitMQ
  include_tasks: rabbitmq_config.yml
  when: >
        rabbitmq_enable_clustering and
        rabbitmq_config is defined

- name: Manage RabbitMQ users
  include_tasks: rabbitmq_users.yml
  # when: rabbitmq_users is defined
